
# aliyun oss配置
oss:
  access-key-id: ${OSS_ACCESS_KEY_ID} # 从环境变量中获取
  access-key-secret: ${OSS_ACCESS_KEY_SECRET}
  bucket-name: mini-programm
  callback-url: http://localhost:8080/oss/upload   #回调地址
  endpoint: mini-programm.oss-cn-beijing.aliyuncs.com  # 存储空间
  expire-time: 3600 # 签名过期时间 默认1小时

