server:
  port: 8080


spring:
  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://cd-cdb-chi3okas.sql.tencentcdb.com:23033/mini_program
    username: zhu
    password: zhu123456

# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

#jwt配置
jwt:
  secret-key: ODIyNjA4Njc3NTIyODE2NjYxMDE3NDIyMjUwMDgxMjgwMjU0MDM2Mzc0MzU4NDc1Nzg2MzM0ODA1MDgxMjM2Mg==
  expiration-time: 604800

# jwt拦截器放行路径
jwt-properties:
  exclude-paths:
    - /login/user
    - /login/admin


# aliyun oss配置
oss:
  access-key-id: LTAI5t9uR1xN1GRPXpxVUwQ2
  access-key-secret: PqDDxxnGypD9El4NEyDXRZe6sRigAk
  bucket-name: mini-programm
  callback-url: /oss/upload#  回调地址
  endpoint: mini-programm.oss-cn-beijing.aliyuncs.com  # oss-cn-beijing.aliyuncs.com
  expire-time: 1800  # 7天

#BCrypt配置
bcrypt:
  strength: 10 # 密码加密强度


logging:
  level:
    root: info

springdoc:
  swagger-ui:
    csrf:
      enabled: true
  api-docs:
    enabled: true

