server:
  port: 8080

wechat-miniProgram:
  appId: ${APP_ID}
  appSecret: ${APP_SECRET}

spring:
  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #本地
#    url: jdbc:mysql://localhost:3306/mini_program?rewriteBatchedStatements=true
#    username: root
#    password: 123456
    url: jdbc:mysql://rm-bp174c3vs31q6c5z9po.mysql.rds.aliyuncs.com:3306/mini_program?rewriteBatchedStatements=true&useServerPrepStmts=true
    username: Xu
    password: Xu1234567

#  web:
#    resources:
#      static-locations:
#        - classpath:/META-INF/resources/
#        - static/**
  # 环境配置
  profiles:
    active: dev
# redis配置
  data:
    redis:
      timeout: 3000
      lettuce:
        pool:
          enabled:  true
          max-idle: 50 # 最大空闲连接数
          max-wait: 500ms
          max-active: 200
          min-idle: 20 # 最小空闲连接数
          time-between-eviction-runs: 30 # 连接空闲时间
        shutdown-timeout: 1000  # 销毁线程等待时间
        cluster:
          refresh:
            adaptive: false
      host: localhost
      port: 6379
      password: zxcvbnm
      ssl:
        enabled: false


# mq配置
  rabbitmq:
    virtual-host: mini_program
    port: 5672
    username: mini_program
    password: 123456
    host: localhost
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000
          multiplier: 2.0


bloom-filter:
  productConfig:
    expectedElements: 500
    fpp: 0.01
  user-config:
    expected-elements: 500
    fpp: 0.01
  order-config:
    expected-elements: 500
    fpp: 0.01

# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#  type-handlers-package: com.zhuxi.handler

#jwt配置
jwt:
  secret-key: ODIyNjA4Njc3NTIyODE2NjYxMDE3NDIyMjUwMDgxMjgwMjU0MDM2Mzc0MzU4NDc1Nzg2MzM0ODA1MDgxMjM2Mg==
  expiration-time: 604800 #


# jwt拦截器放行接口
jwt-properties:
  exclude-paths:
    - /oss/upload
    - /error
    - /swagger-ui.html/**
    - /swagger-ui/**
    - /v3/api-docs/**
    - /admins/login
    - /wechatAuth/login
    - /
    - /1.html

user-access-paths:
  paths:
    - /Order/**





# aliyun oss配置
oss:
  access-key-id: ${OSS_ACCESS_KEY_ID}    # 从环境变量中获取
  access-key-secret: ${OSS_ACCESS_KEY_SECRET}
  bucket-name: mini-programm
  callback-url: http://localhost:8080/oss/upload   #回调地址
  endpoint: mini-programm.oss-cn-beijing.aliyuncs.com  # 存储空间
  expire-time: 3600 # 签名过期时间 默认1小时

OSS-Prefix: https://mini-programm.oss-cn-beijing.aliyuncs.com/

#BCrypt配置
bcrypt:
  strength: 10 # 密码加密强度

# 日志配置
logging:
  level:
    root: info
#    root: debug

# swagger配置
springdoc:
  swagger-ui:
    csrf:
      enabled: true
  api-docs:
    enabled: true

init-Data:
  page-size: 500   #  初始化数据的分页查询页大小




